//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImDone
{
    using System;
    using System.Collections.Generic;
    
    public partial class sapnu_puas
    {
        public string nombre_cine { get; set; }
        public string localidad_cine { get; set; }
        public string telefono_cine { get; set; }
        public string nombre_sala { get; set; }
        public string nombre_genero { get; set; }
        public string titulo_pelicula { get; set; }
        public string nombre_protagonista { get; set; }
        public string Periodo { get; set; }
        public string tipo_tarifa { get; set; }
        public decimal precio { get; set; }
        public string nombre_clasificacion { get; set; }
    }
}
